name: Auto Update Bing Images CI

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"  # UTC时间1点（北京时间9点）
  push:
    branches: [gh-pages]
    paths:
      - 'assets/js/bing.js'
      - 'assets/json/images.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: npm install axios cheerio

      - name: Run Bing Image Script
        run: node ./assets/js/bing.js

      - name: Commit changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add ./assets/json/images.json
          git commit -m "[Bot] Update Bing images $(date +'%Y-%m-%d')"
          git push
